### ISSUE TITLE
test

### ISSUE THREAD

**Issue by PeterLuoCoder** [zyxu1996/Efficient-Transformer#7]
Hi, your test code is a multi-GPU test, but I'm using a single GPU for training, how can I change the test code? I ask you to help me.

**Comment by PeterLuoCoder** [comment]
When I train the DANet model, the results are shown in the figure, and the results do not reach the results in Table 10
![1](https://github.com/zyxu1996/Efficient-Transformer/assets/92514953/a3212974-850e-4b8f-87df-dbbfec3c87ed)
 of your paper.

**Comment by PeterLuoCoder** [comment]
When I train the DANet model, the results are shown in the figure, and the results do not reach the results in Table 10 of your paper.
![1](https://github.com/zyxu1996/Efficient-Transformer/assets/92514953/ddd033f1-ef35-42c2-919b-46f23b1f26a9)

**Comment by zyxu1996** [comment]
> When I train the DANet model, the results are shown in the figure, and the results do not reach the results in Table 10 of your paper. ![1](https://user-images.githubusercontent.com/92514953/241550198-ddd033f1-ef35-42c2-919b-46f23b1f26a9.png)

BatchSize is a very important param that affects the accuracy. You may consider setting it according to the advice in the paper

**Comment by zyxu1996** [comment]
> Hi, your test code is a multi-GPU test, but I'm using a single GPU for training, how can I change the test code? I ask you to help me.

Set the testing shell like this, CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2

**Comment by Sixsheepdad** [comment]
I used:

CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.run --nproc_per_node=1 --master_port 29506 test.py --dataset vaihingen --val_batchsize 16 --models swinT --head mlphead --crop_size 512 512 --save_dir work_dir --base_dir ../../ --information num1 

 but got an  error:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/Efficient-Transformer-main/test.py", line 184, in <module>
    potsdam_val = potsdam(base_dir=data_dir, train=False,
  File "/content/gdrive/MyDrive/Efficient-Transformer-main/dataset.py", line 33, in __init__
    with open(txt, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '../../data/vaihingen/annotations/test.txt'
[2023-11-01 04:09:45,633] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 21953) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 810, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
test.py FAILED

Can you help  me?
